### ISSUE TITLE
gettransaction_MP returns tx data

### ISSUE THREAD

**Issue by ghost** [mastercoin-MSC/mastercore#1]
Make sure gettransaction returns _all_ possible tx data for a specific tx, for example:

https://test.omniwallet.org/explorer/inspector?view=92e5790a7eccddd478b92b14631b64e74425b8c2366179467a5593b3d1325e84

**Comment by dexX7** [comment]
I'm curious. _All_? Half of it is not relevant for a human or Omniwallet, but only for masterchain.info.

Would probably be easier, if you post a list of fields you need.

**Comment by ghost** [comment]
Apologies, this is kind of outdated, see https://github.com/zathras-crypto/mastercore/blob/dac09c5778cb601ec7d247ec34678ae5c3850511/src/mastercoin.cpp#L2258-L2268 for a better schema for this RPC call
