### ISSUE TITLE
Problems with property related queries, client crashes?

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#108]
With dfc8bf57a78aab6fae5b9474ba980047ba0669a3:

Calling `listproperties_MP` and `getgrants_MP` or `getproperty_MP` with a non-existing property id does not always, but sometimes result in a client crash. There is no pattern I could identify.

The last lines in `/tmp/mastercore.log`:

```
update_tally_map(n4ceN5CQ9prW51Ac2TRxjEPw5yfC8cFbu4, 2=0x2, +1000553627, ttype=0); before=0, after=1000553627
msc_file_load(/home/mastercore/.bitcoin/testnet3/MP_persist/balances-000000004c493a7b50e89b59432ea009325bcb2f7611421d6c08ff1d6eb78d84.dat), loaded lines= 37
msc_file_load(/home/mastercore/.bitcoin/testnet3/MP_persist/offers-000000004c493a7b50e89b59432ea009325bcb2f7611421d6c08ff1d6eb78d84.dat), loaded lines= 0
msc_file_load(/home/mastercore/.bitcoin/testnet3/MP_persist/accepts-000000004c493a7b50e89b59432ea009325bcb2f7611421d6c08ff1d6eb78d84.dat), loaded lines= 0
msc_file_load(/home/mastercore/.bitcoin/testnet3/MP_persist/devmsc-000000004c493a7b50e89b59432ea009325bcb2f7611421d6c08ff1d6eb78d84.dat), loaded lines= 1
msc_file_load(/home/mastercore/.bitcoin/testnet3/MP_persist/crowdsales-000000004c493a7b50e89b59432ea009325bcb2f7611421d6c08ff1d6eb78d84.dat), loaded lines= 2
```

Furthermore:

listproperties_MP doesn't return any info:

``` bash
$ bitcoin-cli listproperties_MP
error: {"code":-1,"message":"value is type obj, expected bool"}
```

An example of getgrants_MP crashing the client under some circumstances:

``` bash
$ bitcoin-cli getgrants_MP 2147483657
error: {"code":-8,"message":"Property was not created with a manual issuance"}
$ bitcoin-cli getgrants_MP 1
error: {"code":-8,"message":"Property was not created with a manual issuance"}
$ bitcoin-cli getgrants_MP 2147483657
error: {"code":-8,"message":"Property was not created with a manual issuance"}
$ bitcoin-cli getgrants_MP 2147483655 << *boom*
error: no response from server
```

getproperty_MP returns a strange response, too:

``` bash
$ bitcoin-cli getproperty_MP 1
{
    "name" : "MasterCoin",
    ...
}
$ bitcoin-cli getproperty_MP 2147483657
{
    "name" : "Testing Coin",
    ...
}
$ bitcoin-cli getproperty_MP 2147483655
error: {"code":-1,"message":"value is type obj, expected bool"}
```

**Comment by dexX7** [comment]
I think deleting the MP_\* folders solved the problem.

**Comment by m21** [comment]
from a chat:
      int best_state_block = load_most_relevant_state();
      if (best_state_block < 0) {
        // unable to recover easily, remove stale stale state bits and reparse from the beginning.
        clear_all_state();
      } else {
        nWaterlineBlock = best_state_block;

[12:57:32 PM] zathrasc: nwaterline block is genesis block
[12:57:43 PM] zathrasc: if we read some persistence we set nwaterline to something else
[12:57:49 PM] zathrasc: if not nwaterline is still genesis block
[12:57:53 PM] zathrasc: so at that point
[12:58:02 PM] zathrasc:  msc_initial_scan(nWaterlineBlock + 1);
[12:58:23 PM] zathrasc: couldn't you just say if you're doing your msc_initial_scan from genesis block, clear the slate?
[1:02:45 PM] Michael: sounds about right
[1:02:55 PM] Michael: needs good amount of testing

**Comment by dexX7** [comment]
Resolved for quite some time.
