### ISSUE TITLE
Question: dependency to Bitcoin Core

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#12]
At least on the first glimpse it looks like there was the choice to create a new LevelDB connector instead of using leveldbwrapper.cpp and leveldbwrapper.h. Now I'm not sure, if it were even possible, but that was only what made me think.

What is the general plan for Master Core? Should it be done in a way that most parts are not dependant on Bitcoin Core or is it preferred to reuse as much as possible? I see reasons for both directions.

**Comment by m21** [comment]
My design approach to Master Core:
1. Utilize Core's key Bitcoin-handling functions & methodology: classes, methods, functions, wrappers, etc. Stay at the highest level of those internal low-level functions as much as possible. :)
2. Keep proactive track of upcoming Bitcoin-functionality changes.
3. On general-purpose functionality - no explicit reliance on existing code. Perhaps short term. Those things are way more fluid than Bitcoin-specific components.
4. Do not crash the Core for MP-related reasons (we can't use hard throws, exits, etc.)
5. Do not depend on specific serialization, file/output formats the Core has -- again no guarantee they'll not change tomorrow.

#3, #4 & #5 pretty much ruled out using CLevelDBWrapper.

**Comment by dexX7** [comment]
Awesome, thanks for the answer.

> ... again no guarantee they'll not change tomorrow.

Good point actually. It looks like there are currently quite a lot changes ongoing and coming in the near future, related to Bitcoin Core, for example:
- [Remove cli functionality from bitcoind](https://github.com/bitcoin/bitcoin/commit/b750cf1fb9b6529ab1761b22947677ca78a2c626)
- [Estimatefee / estimatepriority RPC methods](https://github.com/bitcoin/bitcoin/commit/171ca7745e77c9f78f26556457fe64e5b2004a75) + [smart fees in general](https://github.com/bitcoin/bitcoin/pull/4250)
- [Add new "bitcoin-tx" command line utility](https://github.com/bitcoin/bitcoin/pull/4332)

Notable quote:

> This utility is also an intentional exercise of the "bitcoin library" concept. It is designed to require minimal libraries, and works entirely without need for any RPC or P2P communication.

Anyway, I'm very happy to see where this (mcore) is going. :)
