### ISSUE TITLE
Have an RPC to get a list of Smart Properties

### ISSUE THREAD

**Issue by Nevtep** [mastercoin-MSC/mastercore#13]
This is a requirement for the Omniwallet, we need to be able to retrieve a list of properties (and their info) preferably filtered by ecosystem (test or production). At the very least we need to have this info: ID, Name, Issuance Address, Category, Subcategory.

This can then be used to get a list of property categories and subcategories, show active crowdsales, and list previous properties for appending or replacing them.

**Comment by ripper234** [comment]
Note - the list can grow to be quite big over time.

You may want to define some sort order / paginatnation support (e.g. give me the first 100 properties sorted by Name).

The choice of which sort orders are supported is critical here, and should be derived from the use cases that we choose to support in Omni.

@Nevtep, can you specify the intended use case here with all the details?

**Comment by Nevtep** [comment]
This are the use cases I can think of:
1. The Create Crowdsale page needs to list available currencies that the issuer would like to receive, filter by name keyword and having a max . 
2. When editing Smart Properties we need to list properties issued by the issuer address, this should be a fllter.
3. Both Smart Property issuance pages needed to display current created categories/subcategories, but I think we are going to have fixed lists for that, so maybe Category/Subcategory isn't needed after all.

**Comment by ripper234** [comment]
1. Filtering should never be by name only - remember that name isn't unique in the system, and should always come with an attached ID.

I actually think it's a risk to allow someone to type in a name in there, as they may mistype and fail to check on the ID (or just fail to check on the ID and choose the first one).

I would have two default currencies: BTC and MSC, and any additional currency should be by ID only. Once you type in the ID, you see the name of that currency.

So in this use case, I argue there is no need for this RPC call.
1. So this API would be something like getAllCurrencyIDsIssuedByAddressX(address) that returns a list of currency IDs? This is simple enough, I think it shouldn't be a problem, and we don't even need pagination for that.
2. Right, we'll have a fixed list + maybe a freetext field, but we don't need to query all SPs for that.

**Comment by m21** [comment]
https://github.com/mastercoin-MSC/mastercore/blob/michael-0921/doc/apidocumentation.md#listing-master-protocol-properties
