### ISSUE TITLE
Behavior of pending balance

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#137]
I'd like to continue the valuable discussion about pending balances (https://github.com/mastercoin-MSC/mastercore/commit/eead8a5078bcaa80e9518def8418398c961fdba4#commitcomment-7916570) and I think I noticed a bit strange behavior.

When I move coins from A to B:
- A's balance is reduced
- B's remains the same (that was expected given your info)

When I then move coins from B to A:
- A's balance increases
- B's balance remains untouched

So basically A's balance was accurate all the time, but B's balance never changed, despite being actor. The following chain of transactions might be a bit long, but I added the math for each step as info.

All was run via a script after clean reboot etc. to confirm what I saw yesterday already, but didn't save:

---

Start:

```
bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "14.60067819",
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700",
    "reserved" : "0.00000000"
}
```

```
bitcoin-cli send_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2 4
d0c8b34b716ef81a21e92d1452530600cc0c9ec311c362f57c367abc282f7f11

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "10.60067819", < 14.60067819 - 4.0 = 10.60067819
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 = 16.29906700
    "reserved" : "0.00000000"
}
```

```
bitcoin-cli send_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2 10
655793399448ca627981f6d53efe1de1ef42b5bd8023254f802988b0cbfe5333

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "0.60067819", < 14.60067819 - 4.0 - 10.0 = 0.60067819
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 + 10.0 = 26.29906700
    "reserved" : "0.00000000"
}
```

Note how n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ is now sender:

```
bitcoin-cli send_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2 10
0f3ef434de3e98318285d92d62cae4be67eecc56a25839bebcaf27d89f96c0df

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "10.60067819", < 14.60067819 - 4.0 - 10.0 + 10.0 = 10.60067819 (increase!)
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 + 10.0 - 10.0 = 16.29906700 (unaffected!)
    "reserved" : "0.00000000"
}
```

```
bitcoin-cli send_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2 2
db395a22df30af15302c339e6a3eb8a8cc8908b8fdf8c1643e716fbc79ae38bf

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "12.60067819", < 14.60067819 - 4.0 - 10.0 + 10.0 + 2.0 = 12.60067819
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 + 10.0 - 10.0 - 2.0 = 14.29906700
    "reserved" : "0.00000000"
}
```

mvayzbj425X55kRLLPQiuCXWUED6LMP65C is sender again:

```
bitcoin-cli send_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2 0.6
8f2040415ae3b547903e5e3ef6394818baf1a7e497d50c74759c3b5292776373

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "12.00067819", < 14.60067819 - 4.0 - 10.0 + 10.0 + 2.0 - 0.6 = 12.00067819
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 + 10.0 - 10.0 - 2.0 + 0.6 = 14.89906700
    "reserved" : "0.00000000"
}
```

n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ is sender:

```
bitcoin-cli send_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2 0.2
85ec5480aac186bfc9e4e82d706de76dd2c42cfb2facd1f84875fd2f59a69078

bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "12.20067819", < 14.60067819 - 4.0 - 10.0 + 10.0 + 2.0 - 0.6 + 0.2 = 12.20067819
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "12.29906700", < 12.29906700 + 4.0 + 10.0 - 10.0 - 2.0 + 0.6 - 0.2 = 14.69906700
    "reserved" : "0.00000000"
}
```

---

After confirmation:

```
bitcoin-cli getbalance_MP mvayzbj425X55kRLLPQiuCXWUED6LMP65C 2
{
    "balance" : "12.20067819",
    "reserved" : "1.50000000"
}
bitcoin-cli getbalance_MP n4EmA9R4VmxLnxu9G8yZMDxvBBha8bUtEQ 2
{
    "balance" : "14.69906700",
    "reserved" : "0.00000000"
}
```

The final result after confirmation is matches the math.

Edit: for historical reasons: https://github.com/mastercoin-MSC/mastercore/commit/6bfd529584562575f3dced2a992dd09f123b7acf untouched was used.

**Comment by zathras-crypto** [comment]
@Michael, the adding of positive values to pending thus skews the process in a chain of transactions.
I think we should not add positive pending balances, the use case (immediate use case anyway) is to ensure balances are reduced with outbound transactions.  Adding positive values to the recipients pending balance seems to serve no immediate purpose since we specifically only use the pending value if it's negative.

**Comment by m21** [comment]
Makes sense, just wanna bounce it off @dexX7 
I do track increases in amounts due to pending TX, but do not display it which does confuse the total balance displayed as Dexx7 found out.

Zathras' suggestion is to only track (temp/pending) decreases in balances and act on them accordingly in various Send functions (RPC & UI) and display them as such.

Are we all in agreement thast this is the best user-interface approach?

**Comment by dexX7** [comment]
I have no QT client running at the moment, but how is it handled there?

To the level of details:

I think `balance` and `reserved` is not enough, especially if it's a bit untransparent what actually counts and what not. If we break it down (to the extreme), there is:
- confirmed balance
- confirmed amount reserved for accepts
- confirmed amount reserved for sells
- unconfirmed amount sent internally
- unconfirmed amount received internally
- unconfirmed amount sent to an external receiver
- unconfirmed amount received from an external sender

And maybe "unconfirmed amounts from accepts/sells" and likewise from/to crowdsales etc..

In my opinion the RPC interface should provide the highest level of detail, so developers can pick what they need, while the UI can use (much) less and should be task/user intent centric.

I don't suggest to dump it all, but rather try to get an overview. :)

---

Let's take a look at Electrum - which I consider as one of the best clients out there:

Sequence:

Start -> Send 2 BTC to myself -> Send 0.1 BTC to an external wallet -> Receive 0.0999 BTC from an external wallet:

![electrum](https://cloud.githubusercontent.com/assets/5836089/4424375/90af0cf8-459e-11e4-8197-8369cf1cf2a1.png)

Unfortunally the pending transactions are out of order, but there are basically two balances and this behavior:
- The balance on the right in the history tab shows "what could be spent"
- The balance at the bottom shows the confirmed actual balance + unconfirmed amount
- Internal sends are completely ignored, besides fee

---

And are you in contact with the Omni team?

The [database schema](https://github.com/marv-engine/omniwallet/blob/master/database/omni_db_schema.psql#L160-L162) suggests there is an "available", "reserved" and "accepted" balance. I assume this basically mirrors `MONEY`, `SELLOFFER_RESERVE` and `ACCEPT_RESERVE`. I'm not sure how they want to handle unconfirmed amounts, but the scheme suggests furthermore a transaction has [one of the following states](https://github.com/marv-engine/omniwallet/blob/master/database/omni_db_schema.psql#L30): "pending", "valid" and "not valid", so I assume the current plan is to derive unconfirmed amounts from pending transactions similar to what I initially mentioned as possible workaround.

**Comment by dexX7** [comment]
> ... the use case (immediate use case anyway) is to ensure balances are reduced with outbound transactions.
> 
> Zathras' suggestion is to only track (temp/pending) decreases in balances and act on them accordingly in various Send functions (RPC & UI) and display them as such.

I think this is the best first step. The initial problem was:
1. no reliable balance information whenever there are pending transactions which can't be fetched
2. no guard against overspending and sending new transactions while there are no coins left

Focusing on the protection against overspending should have the highest priority in my opinion.

Edit: ... **without turning mastercore into a blackbox with unpredictable behavior.**

Imho this is the utmost important point - always. :)

**Comment by dexX7** [comment]
This is sort of related to #93. While there are several areas where behavior in relation of unconfirmed transactions can be improved, there is no immedient task to do. /close
