### ISSUE TITLE
Run tests automatically upon commit (Add Jenkins trigger as Github Service)

### ISSUE THREAD

**Issue by msgilligan** [mastercoin-MSC/mastercore#145]
1. Go to the Github _Settings_ page for this repository
2. Click on the _Webhooks & Services_ menu (left hand side)
3. Click _Add service_ (to the right of _Services_)
4. Select _Jenkins (Github Plugin)_
5. Set the _Jenkins hook url_ to `http://ci.mastercoin.info/github-webhook/`
6. Click _Update service_

Then next time a commit is made to the `mscore-0.0.8` branch, the database schema will automatically be tested.

**Comment by dexX7** [comment]
This will probably be extremely useful. Is there any chance this works with pull requests as well?

And since the 0.9.3 integration seems to work already: does this change anything?

**Comment by msgilligan** [comment]
@dexX7: We're currently running build & test jobs manually with the Jenkins _Build now_ button. Once the "Jenkins hook" is set up, the jobs will run automatically when a commit is made on a configured branch. I can also configure a build for the `mscore-0.0.8` branch and one for the `mscore-0.0.9` branch. The Jenkins hook will ping a URL on the Jenkins server upon any commit. The Jenkins server can then be configured to run as many jobs from as many different branches as we want to configure and maintain.

Suggestions are definitely welcome.

**Comment by dexX7** [comment]
Ah, thanks for the information. I think I can't contribute much to this topic, but I asked about 0.9.3 in particular, because it looks like Travis CI became part of bitcoin:master recently and I was under the assumption this was already part of 0.9.3 (which actually doesn't seem to be the case).

**Comment by dexX7** [comment]
Now that I think about it.. could this system be used to build nightly builds?

**Comment by msgilligan** [comment]
Yes, we could create a job for nightly builds, but we'd need to perform a security audit of the Jenkins server before making those available for download. For now, the focus of the Jenkins server is on testing and we are not recommending or making available to others the built artifacts.

**Comment by achamely** [comment]
setup
