### ISSUE TITLE
RPC command: mscrpc

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#164]
The RPC command `mscrpc` seems to dump the content of the leveldb files which is actually a sweet thing, but do you use it and does this need to be included within releases?

Maybe a startup flag such as `--mscdev` could be implemented which hides such a call, if not provided.

**Comment by m21** [comment]
It's undocumented, I use it primarily in development. It takes numeric parameters (sometimes one sometimes two), like so:
mscrpc 0 1
mscrpc 1
mscrpc 6
But shhhhh, please don't tell anyone, it's very unsupported and prone to breaking. :)
