### ISSUE TITLE
Price everything in MSC

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#200]
This is mostly directed @zathras-crypto:

If Master Core indeed enforces trading of MSC or TMSC on one side of a meta DEx trade on the UI level, then I suggest to price everything in MSC. I tested 0.0.9-Z-UIAlpha more than once, but showing the unit price isn't really great nor useful. I suggest to show prices-in-MSC on both sides of a  trade instead.

**Comment by m21** [comment]
I am sure @marv-engine would be interested, maybe @dacoinminster  as well. :)

**Comment by dexX7** [comment]
Sure, the more opinions there are on this, the better.

**Comment by zathras-crypto** [comment]
Hey DexX,

Could you elaborate a bit mate?

The prices (including unit prices) should be set in MSC.

For example:
BUY:
Enter price per SPT & number of tokens to buy, UI will auto calculate the
fixed MSC total to be spent.  When listed this order is then inverted into
a sell MSC for SPT.

SELL:
Enter price per SPT & number of tokens to sell, UI will auto calculate the
minimum MSC total to be received.

Appreciate any suggestions as always mate :)

Thanks
Z

**Comment by dexX7** [comment]
Yeah sure, here is a Paint mockup of the underlying concept:

![seperation](https://cloud.githubusercontent.com/assets/5836089/5037983/ed20510a-6b8b-11e4-9a97-69da7d6f87ec.png)

Transformed into Master Core:

![mockup](https://cloud.githubusercontent.com/assets/5836089/5037972/d8474f18-6b8b-11e4-8894-a8a9f76b4a48.png)

Changes:
- Swap buy and sell offers area (is there any exchange where this is the other way around?)
- Show units as whole units, if not divisible
- Order by price
- Move price column close together
- Show price nominated in MSC

Edit: tradeblock.com:

![tradeblock](https://cloud.githubusercontent.com/assets/5836089/5038163/03ef99de-6b8e-11e4-9bad-6a459be91a1a.png)

**Comment by dexX7** [comment]
This seems to be material for @zathras-crypto UI integration for Omni Core: https://github.com/OmniLayer/omnicore/pull/5, and should be reevaluated over there.

**Comment by zathras-crypto** [comment]
FYI @dexX7 the UI does now price everything in MSC.

As you probably have seen there is a normal sell side and a 'fake' buy side
(since there is no concept of a buy on MetaDEx) - the buy side is just
using the inverted price so we can reflect "sell MSC for SPT" as"buy SPT
with MSC" keeping it simple for the end user - this way all prices can be
in MSC.

I'm not sure this should apply to RPC though (don't think it does but been
many moons since I looked at MetaDEx RPC calls hehe)
