### ISSUE TITLE
Cancel-at-price: "Not enough funds in user address"

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#217]
1) A1 starts with 50.0 TMSC, 0 TIndiv1
2) A1 offers 50.0 TMSC for 100 TIndiv1
3) A1 cancels 50.0 TMSC for 100 TIndiv1 (cancel-at-price)

This fails with the message _"Not enough funds in user address"_.

Related test lines: [test_cancel_at_price.py#L307-L356](https://github.com/dexX7/mastercore-rpc-tests/blob/5f78df713e6adbfae0fdc3b486fcd5a10122a470/test_cancel_at_price.py#L307-L356)

**Comment by zathras-crypto** [comment]
Thanks DexX, not sure what's going on here - great testing :)

**Comment by dexX7** [comment]
It probably comes from `mastercore::send_INTERNAL_1packet` and it looks like as if the user's balance would be used for a check like this:
1. Start: 50.0 available, 0.0 reserved
2. Create: 0.0 available, 50.0 reserved
3. Cancel: fail, because available < amount-to-cancel

The "cancel" seems to be treated as "send", thus a check against the balance. What makes me wonder a bit: "cancel-pair" and "cancel-everything" is explicitly excluded as it seems, but a "cancel-at-price" not. ([mastercore.cpp#L2908](https://github.com/mastercoin-MSC/mastercore/blob/mscore-0.0.9/src/mastercore.cpp#L2908))

**Comment by ghost** [comment]
Good catch Dexx, I think this was due to an erroneous assumption on my part (that the user actually needed to check if they had the funds for any cancel - which is not needed)

Added cancel-price to exclusions list, and renamed variables: https://github.com/mastercoin-MSC/mastercore/pull/221/files

**Comment by dexX7** [comment]
@faizkhan00:
I'm testing the current master and it seems the test still fails, but based on some other effect:

The cancel itself seems to have no effect anymore.

This is limited to the special case where "amount-to-cancel" > "available-balance" and the other tests of cancel-at-price finish as expected.

---

1) A1 starts with 50.0 TMSC, 0 TIndiv1:

Orderbook: empty
Balance: 50.0 TMSC available, 0.0 TMSC reserved

2) A1 offers 26.0 TMSC for 100 TIndiv1

Orderbook: 26.0 TMSC offered for 100 TIndiv1
Balance: 24.0 TMSC available, 26.0 TMSC reserved

3) A1 cancels 26.0 TMSC for 100 TIndiv1 (cancel-at-price):

Orderbook: **26.0 TMSC offered for 100 TIndiv1**
Balance: **24.0 TMSC available, 26.0 TMSC reserved**

**Comment by dexX7** [comment]
This was fixed by #221 and #222.
