### ISSUE TITLE
Cancel-everything: "Property identifier does not exist (Want)"

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#218]
Via RPC interface:

1) A1 starts with 50.0 TMSC, 50.0 TDiv1 and 0 TIndiv1
2) A1 offers 50.0 TMSC for 500 TIndiv1
3) A1 cancels everything in the main ecosystem (0.0 TDiv1, 9000 of a non existing test property)

This fails with the message _"Property identifier does not exist (Want)"_.

Related test lines: [test_cancel_everything_values.py#L173-L203](https://github.com/dexX7/mastercore-rpc-tests/blob/5f78df713e6adbfae0fdc3b486fcd5a10122a470/test_cancel_everything_values.py#L173-L203)

This is due to the input validation checks, but in the case of cancel-everything amounts and property identifiers should be ignored, as long as both properties are in the same ecosystem.

**Comment by zathras-crypto** [comment]
Same comment as other, cancel everything ambiguous.
- CANCEL EVERYTHING = "Cancel every sell offer"
- CANCEL EVERYTHING = "Cancel every sell offer _in the ecosystem matching the supplied pair_"

First option is coded now AFAIK.

**Comment by dexX7** [comment]
Either way (with or without ecosystem limitation), there should not be a property id validation, I think.

Edit: similar to how some other fields are ignored, such as amounts that can be zero. (...)

**Comment by ghost** [comment]
can you provide a use case for why this behavior needs to be added? if you have an active trade, its very easy to just supply the proper propertyid to make the RPC call return successfully

Additionally as Zathras mentioned depending on future implementation changes this will need to be checked (if cancel_all is applied per-ecosystem rather than cross-ecosystem)

**Comment by dexX7** [comment]
I have no explicit use case, but everything in the Mastercoin "system" is build around the concept of two seperated ecosystems that can't interact with each other. A "cancel-everything" that is not limited to one ecosystem breaks this.

**Comment by dexX7** [comment]
Oh, sorry, wrong thread.

> Additionally as Zathras mentioned depending on future implementation changes this will need to be checked (if cancel_all is applied per-ecosystem rather than cross-ecosystem)

I do not suggest do ignore property identifiers completely, but it should not matter, if they are valid. Similar to how amounts are ignored in the case of "cancel-pair" and "cancel-everything", there should be no validation of the property values. But if "cancel-everything" is indeed limited to one ecosystem, then the property values should be used to determine the ecosystem - until there is an explicit field, as suggested here: https://github.com/mastercoin-MSC/spec/pull/276#issuecomment-60843476

Two scenarios:

1) If "cancel-everything" is not limited to an ecosystem:
- amount values should be ignored
- property values should be ignored

2) If "cancel-everything" is limited to an ecosystem:
- amount values should be ignored
- property values are used to determine the ecosystem
- contradicting values should not be allowed (e.g. MSC, SomeTestEcosystemProperty)
- it could be acceptable, if only one property value is given and the other is zero

**Comment by dacoinminster** [comment]
I think it is not limited to an ecosystem currently, and the spec should reflect that.

**Comment by dexX7** [comment]
Resolved with PR #224 and #226.
