### ISSUE TITLE
clang analysis

### ISSUE THREAD

**Issue by m21** [mastercoin-MSC/mastercore#253]
https://github.com/mastercoin-MSC/mastercore/pull/243#issuecomment-66916919

in reference to the above is ExodusValues[0] the only concern of the tool?
The function exits if marker_count is 0; marker_count is only incremented if ExodusValues[0] gets something assigned to it, so probably not an issue. I'll initialize the array anyway. Thanks!

**Comment by m21** [comment]
Delivered a while back:
https://github.com/mastercoin-MSC/mastercore/blob/mscore-0.0.9/src/mastercore.cpp#L1079

**Comment by dexX7** [comment]
Strange, I assumed I answered here.

@m21: Yes, this was the only significant thing Clang's static analyzer found. However, there is more when running [Coverty Scan](https://scan.coverity.com/projects/3764/view_defects), but the only tagged-as-important finding has basically no pratical relevance at this point and I submitted a fix with https://github.com/mastercoin-MSC/mastercore/pull/258 a while ago.

![oob](https://cloud.githubusercontent.com/assets/5836089/5603572/0a8847e8-938c-11e4-9f23-86288eef80e0.png)
