### ISSUE TITLE
Need: bitcoin-"send to owners" RPC call

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#262]
This seems almost redundant to `sendmany` and one may just create a list of owners and create the transaction via some other means, but since an explicit call would be much easier, I suggest to implement a "send to owners" RPC call for bitcoin.

I'll sign up for this task, but I'm not sure, if I get this ready within the next days due to xmas.

Related: #261

**Comment by m21** [comment]
I am confused, we have this:
https://github.com/mastercoin-MSC/mastercore/blob/mscore-0.0.9/doc/apidocumentation.md#broadcasting-a-send-to-owners-transaction

**Comment by dexX7** [comment]
This doesn't work for Bitcoin, but only token transactions. I say it's almost trivial, because it can be done manually, but since it's often named in "comparisons of different meta-coin systems", I suggest to do it.

**Comment by m21** [comment]
sendtoowners_MP works for MSC, TMSC and all SP on Master Protocol.
You are probably suggesting sending some BTC to all owners of MP-properties? Proportionally? That sounds like something that would need to be added to the spec first.

**Comment by dexX7** [comment]
> You are probably suggesting sending some BTC to all owners of MP-properties?

Correct.

> That sounds like something that would need to be added to the spec first.

A note in the spec wouldn't hurt, that's true. Strictly seen it's not a Master protocol transaction, but combining Core functions, but an explicit data package to tag such a transaction for easier identification by transaction explorers would be great.

In this context: https://github.com/mastercoin-MSC/spec/issues/298

**Comment by m21** [comment]
Thinking a bit more -- the current STO MP command does not actually "send" anything to the actual owners (no blockchain entry for those destination addresses).
So the change to the sendtoowners_MP command you are proposing is actually more drastic than appears on first glance. Please conitnue in the spec instead.

**Comment by zathras-crypto** [comment]
Just clarifying here - a bitcoin STO has absolutely nothing to do the the
MP and is not issued via the MP.  Sure you may use MP _balances_ to
determine to whom and how much BTC you are going to send, but there is no
protocol packet to parse, just a bitcoin transaction with a bunch of
outputs.

As such, the Q stands as should this be a Omni Protocol function?

I actually think it will be useful for integrators, but agree on
prioritization - if no-one is asking for it yet, let's put it on the
backburner.
