### ISSUE TITLE
Release:  Confirm Windows binaries provide same data

### ISSUE THREAD

**Issue by zathras-crypto** [mastercoin-MSC/mastercore#294]
I'd like Jenkins to run tests against the windows binaries.

I've prepared a windows instance with 0.0.9.1 binaries @ 52.11.127.145 - it's just catching up the blockchain from my last image - if @dexX7 @msgilligan one of you guys wants to ping me the IP Jenkins will be connecting from I'll open up the RPC port for Jenkins to run RPC queries on.

Thanks
Z

**Comment by dexX7** [comment]
You actually can run the tests locally on Windows. :)

1) Install JDK version 7 or 8 (e.g. [Oracle JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html))

2) Clone https://github.com/msgilligan/bitcoin-spock.git

3) _Just to confirm_: create a new `bitcoin.conf` with the following content:

```
server=1
rpcuser=bitcoinrpc
rpcpassword=pass
rpcallowip=127.0.0.1
txindex=1
debug=1
logtimestamps=1
regtest=1
```

4) Start `mastercore-qt` _and use that config_. This should start Omni Core in regtest mode.

5) Go to the `bitcoin-spock` dir and enter in a cmd:

```
C:\...\bitcoin-spock>gradlew.bat regTest
```

6) Once finished, shutdown the client.

You can find a shiny test report here:

```
C:\...\bitcoin-spock\build\reports\tests\index.html
```

7) Edit or replace the `bitcoin.conf` and remove the `regtest=1` line:

```
server=1
rpcuser=bitcoinrpc
rpcpassword=pass
rpcallowip=127.0.0.1
txindex=1
debug=1
logtimestamps=1
```

Be careful: you're going to operate on mainnet, so move important `wallet.dat` files, if there are any.

8) Start the consensus tests via:

```
C:\...\bitcoin-spock>gradlew.bat consensusTest
```

There are a few very nice extensions in the context of consensus testing, but this is pretty much what's going on on the CI server.

If I'm not mistaken, then consensus is checked against Chest, Omni Wallet and a "stable" other server.

Edit: the client very likely won't be fully responsive during the tests.

I'm unfortunally unable to do run tests on the CI server against your server, but @msgilligan probably can.

**Comment by zathras-crypto** [comment]
Awesome thanks, I'll try this as soon as the sync is done (t2.medium's on AWS don't sync too fast but they're cheap).

I think what I'll do is make some windows (via mingw) and linux x64 binaries and modify the version to say be `0.0.9.1-rc1internal` and send these to everyone internally to play with and then provided there are no glaring problems (hopefully people will actually test it) we can then tag `0.0.9.1-rel` properly and publish proper signed binaries (preferably via gitian).  I intend to raise the howto/landing page stuff at the meeting in the morning too FYI.

**Comment by dexX7** [comment]
Well, see my update in the other thread.

FWIW: the Windows x64 binary is in consensus and passes all tests, run locally on my machine with Windows 8.1 a few minutes ago:
- http://bitwatch.co/uploads/0.0.9.1-dev-win-consensus/
- http://bitwatch.co/uploads/0.0.9.1-dev-win-regtest/

**Comment by zathras-crypto** [comment]
Windows data is sound as confirmed by @msgilligan & @dexX7
