### ISSUE TITLE
Write a blog post about Master Core

### ISSUE THREAD

**Issue by ripper234** [mastercoin-MSC/mastercore#3]
When is that scheduled?

BTW, it's "Master Core" and not "Mastercore", right?

**Comment by m21** [comment]
Now that's a good question, so: 1 word or 2 ? Opinions please.

**Comment by dacoinminster** [comment]
J.R. does not care. I nominate Michael to name it, since it wouldn't have
happened without him :)

**Comment by enmaku** [comment]
I concur with the naming rights issue.

I can also post something today, as soon as a certain someone chimes in on how I should spell a certain important word that's likely to appear a few times in the text ;-)

Thanks,
Dave

**Comment by dexX7** [comment]
Well, it's "Bitcoin Core".

**Comment by ripper234** [comment]
+1 Dexx

**Comment by dexX7** [comment]
After thinking a bit more about this. Actually the equivalent would be "Mastercoin Core"? Or maybe even "Master Core", since it refers to the protocol.

But I noticed: in the emails I exchanged I intuitively used "mastercore". So I vote for "Mastercore". :)

**Comment by ripper234** [comment]
Mastercoin does feel natural.

Removing my +1 for Master Core ... Michael - choose whatever you want :)

On Thu, Jun 12, 2014 at 12:57 AM, dexX7 notifications@github.com wrote:

> After thinking a bit more about this. Actually the equivalent would be
> "Mastercoin Core"? Or maybe even "Master Core", since it refers to the
> protocol.
> 
> But I noticed: in the emails I exchanged I intuitively used "mastercore".
> So I vote for "Mastercore". :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mastercoin-MSC/mastercore/issues/3#issuecomment-45805623
> .

## 

Ron Gross
Executive Director, Mastercoin Foundation
mastercoin.org   |   ripper234.com   |   ripper234 on skype (Inbox != Zero
http://ripper234.com/p/how-i-learned-to-let-go-of-inbox-zero/)   |   PGP
http://pgp.mit.edu/pks/lookup?op=vindex&search=0x7468729E28277264
Schedule my time at meetme.so/RonGross

**Comment by zathras-crypto** [comment]
My vote for Master Core.

Our marketing push is functionality on top of bitcoin.
Our development push is functionality on top of Bitcoin Core - hence Master
Core :)

Thanks
Zathras

**Comment by dexX7** [comment]
There is also the question about filenames. I'd prefer mastercored/mastercore-qt over masterd/master-qt.

**Comment by zathras-crypto** [comment]
Agreed - this was discussed in the skype group this morning - final
decision is Michael's but I've done my best to persuade for "Master Core"
(product name) and "mastercored/mastercore-qt" (compiled name).

Thanks
Zathras

**Comment by m21** [comment]
Master Core it is !
Everyone's favorite. Thanks guys

**Comment by ripper234** [comment]
Was something posted on our blog?

**Comment by zathras-crypto** [comment]
Picking up.
@Ron, no nothing has been posted yet.
Discussed, Michael would like to frame this being as his project - has asked if he puts it together in general would I flesh it out - inclined to agree unless David has something already.
Pls advise asap @David if you have done this already, if not let's let Michael adopt.
Thanks
Zathras

**Comment by enmaku** [comment]
I'm happy to hand it over to Michael, it's his spotlight to steal :)

**Comment by m21** [comment]
http://blog.mastercoin.org/2014/06/13/master-core/

off we go, details etc. will follow

Thanks!
