### ISSUE TITLE
move to 0.9.2

### ISSUE THREAD

**Issue by ghost** [mastercoin-MSC/mastercore#34]
https://github.com/faizkhan00/mastercore/commits/0.9.2-merge

This commit contains a test merge, its clean, minus file mode changes

not necessarily speaking we should use that branch, but #1 reason to switch is CentOS compatibility, which we get out of the box

**Comment by m21** [comment]
See here - porting to 0.9.2.1 was confirmed to be very easy:
https://github.com/mastercoin-MSC/mastercore/issues/8#issuecomment-47803999

Will move officially when get more spare cycles.
