### ISSUE TITLE
Adopt a Milestone and issue prioritization schedule

### ISSUE THREAD

**Issue by ripper234** [mastercoin-MSC/mastercore#4]
See:
- https://github.com/mastercoin-MSC/omniwallet/issues/milestones
- https://github.com/mastercoin-MSC/omniwallet/issues (prioritized)

The fact that their roadmap is on github makes it easy to have an intelligent conversation about the roadmap - it's more accessible to other team members.

**Comment by m21** [comment]
Following Zathras' internal document for the initial set of milestones.
