### ISSUE TITLE
P2SH support

### ISSUE THREAD

**Issue by ripper234** [mastercoin-MSC/mastercore#60]
See these patches integrating P2SH into [mastercoin-tools](https://github.com/mastercoin-MSC/mastercoin-tools/pull/66) and [Masterchest](https://github.com/zathras-crypto/masterchest-library/pull/5).

As these tools are deprecated, we should instead integrate that logic into Master Core.

**Comment by dexX7** [comment]
I opened https://github.com/mastercoin-MSC/spec/issues/224 in this context.

**Comment by m21** [comment]
Spec guidance needed.

**Comment by m21** [comment]
Once architecture on this issue appears in the spec -- will schedule for implementation.
