### ISSUE TITLE
Move logging from console to msc_debug.log

### ISSUE THREAD

**Issue by zathras-crypto** [mastercoin-MSC/mastercore#7]
We pump a lot of info to console now which is helpful during development but as we gear up towards a daemon we need to be pushing this info into a log on disk.
Review bitcoin source for how they push to debug.log for code reuse if possible.

**Comment by ghost** [comment]
Agreed, should we pump to debug.log or a new file, msc_debug.log, what would this contain? just output of errors or all of the current info to the console?

**Comment by zathras-crypto** [comment]
My preference is everything that goes to console now is simply redirected into a log for immediate term resolution.
My preference also is to use a new log (msc_debug.log for example) so we can easily follow our own logic

**Comment by dexX7** [comment]
You may use LogPrint ([source](https://github.com/mastercoin-MSC/mastercore/blob/michael/src/util.h#L136) + [more](https://github.com/mastercoin-MSC/mastercore/blob/michael/src/util.cpp#L238)) which can be used this way:

`LogPrint("mastercore", "Found MSC address %s in block %d\n", addr.ToString(), nHeight)`

The first argument is the category.

Categories to log can be specified via the command-line argument `-debug=<category>`:

> Output debugging information (default: 0, supplying <category> is optional)
> If <category> is not supplied, output all debugging information.
> <category> can be: addrman, alert, coindb, db, lock, rand, rpc, selectcoins, mempool, net, qt.

Categories are not registred and you can use anything you want. I saw you are using `LogPrintf` a few times - that's the same as `LogPrint(NULL, ...)`. You'd need to add `-debug` (which logs everything -> very large file!) or `-debug=mastercore` (for example) to the bitcoind startup args to log Mastercore related information.

Or of course you could output to a completely new file by using a modified version of LogPrint (or related).

**Comment by ghost** [comment]
This complaint was brought up in chat regarding logprintf

```
Michael: we can't readily reuse LogPrint  & LogPrintf since they have debug.log name hard-coded :(
[9:49:21 PM] faiz: (brb guys, will be back in a jif)
[9:49:21 PM] zathrasc: ah
[9:50:44 PM] Michael: int LogPrintStr(const std::string &str)
0 guiutil.cpp <global>       351 boost::filesystem::path pathDebug = GetDataDir() / "debug.log";
[9:50:52 PM] Michael: 3 util.cpp    <global>       287 boost::filesystem::path pathDebug = GetDataDir() / "debug.log";
[9:50:57 PM] Michael: 5 util.cpp    DebugPrintInit 231 boost::filesystem::path pathDebug = GetDataDir() / "debug.log";

```

hmm, can we specify a default log level? I think if we copypasted the log functions, rewrote the debug.log line to something like msc_debug.log, and then set the default log level to mastercoin, this is pretty much the definition of 'low-hanging fruit' in terms of client improvements

**Comment by dexX7** [comment]
Well, you guys never used LogPrint, but only LogPrintf which is LogPrint with category=NULL, might be worth to mention this to Michael (just want to be sure, he probably knows anyway :)..

As far as I know per default (this means without `-debug`) everything with category=NULL is logged (see [LogAcceptCategory](https://github.com/mastercoin-MSC/mastercore/blob/michael/src/util.cpp#L238)). With `-debug=0` everything is logged and with `-debug=<categories>` the categories to log are defined.

**Comment by m21** [comment]
thanks guys
most output now goes to /tmp/mastercore.log , hard-coded for now
https://github.com/mastercoin-MSC/mastercore/tree/20b8db5ffaab47cd79e1a225760c29918ac5d677
we can open another issue to beatify it , or just do it some time
