### ISSUE TITLE
Rebase to Bitcoin Core 0.9.2

### ISSUE THREAD

**Issue by ripper234** [mastercoin-MSC/mastercore#8]
http://www.reddit.com/r/Bitcoin/comments/284sek/bitcoin_v092_officially_released/

It contains a security fix of OpenSSL.

**Comment by m21** [comment]
Did a quick manual port of our code to Bitcoin Core 0.9.2.1, took less than an hour. Easy.
Perfect consensus on MSC, 2 Satoshis off on TMSC, known issue with master-tools.

Source is here for now, will move to github when I am a tad less swamped:
https://drive.google.com/file/d/0B1ZIhHKqXQiiQzhMTEJkVm82ODA/

**Comment by ghost** [comment]
awesome!!

**Comment by m21** [comment]
Done. The default branch & code are now based on Bitcoin Core 0.9.2.
https://github.com/mastercoin-MSC/mastercore/tree/michael-0921

First commit: https://github.com/mastercoin-MSC/mastercore/commit/c73356318b9a76891e80163aa99c410e3ae999e1

**Comment by ripper234** [comment]
Very well done @m21 , I'm glad our codebase is easily rebaseable!

**Comment by m21** [comment]
@ripper234 That was one of the original selling points ;p
