### ISSUE TITLE
getallbalancesforaddress_MP behavior?

### ISSUE THREAD

**Issue by marv-engine** [mastercoin-MSC/mastercore#83]
Does getallbalancesforaddress_MP return an object for each property id where there is a non-zero value for any of balance, reservedbyoffer or reservedbyaccept?

**Comment by zathras-crypto** [comment]
getallbalancesforaddress_MP returns zero values also.

The decision on whether to include an address is based on whether the address has transacted in that property ID before.

So for example an address that has never done anything with property ID #3 will not be included, but an address that has received 100 SPT #3 and subsequently sent on the 100 SPT #3 leaving a zero balance will be included.

Thanks
Z
