### ISSUE TITLE
gettransaction_MP throws exception, if transaction is unconfirmed

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#93]
An exception is thrown, if an unconfirmed transaction is fetched.

``` bash
> error: {"code":-5,"message":"Exception: blockHash is 0"}
```

**Comment by zathras-crypto** [comment]
This is correct behaviour, we don't parse transactions until they're confirmed in a block.
Perhaps a more descriptive error would be prudent though.

**Comment by dexX7** [comment]
> correct behaviour

I believe this is a temporary solution?

Related and more critical in my opinion: since unconfirmed transactions are not processed, balances are also not updated. Besides an inaccurate view of world, I could easily end up in a situation where I spend (at least from the user's perspective) coins that are not available.

Currently I'm wondering how I could solve this in a system that frequently sends out coins and the current workaround is to keep a seperated database of transactions and balances. This is probably not the best solution, given the overhead and potential for divergences.

**Comment by zathras-crypto** [comment]
Unconfirmed transactions is an open discussion at the moment mate, there isn't really full agreement about what we will do here.  Michael favours allowing visibility of transactions in mempool but not yet confirmed, but doesn't like the idea of amending the state until a transaction is confirmed.

All open right now - unconfirmed support will come _in some fashion_ as to what that'll look like is undecided at present though - input welcome of course.

When you say 'frequent' do you mean more frequently than per block I'm assuming?

Thanks
Z

**Comment by dexX7** [comment]
Actually it doesn't matter how frequent is defined in this context. The problem arises right from the start:

I can't be sure in any case without additional assumptions about the state of the wallet or external knowledge about previous transactions related to the balance.

An assumption could be "I know the last transaction was sent a longer time ago and therefore I assume there is no pending unconfirmed transaction and the balance information is accurate" or "even given that there are unconfirmed transactions, my balance should be high enough anyway".

---

Re: mempool info in general: extremely useful!

From a logical perspective I think there are different layers and seperated actions related to transaction handling:
1. Basic interpretation based on the transaction itself (such as: transaction type, amounts, ...), could be requested by the user in form of some RPC call like "decoderawtransaction_MP", but also related to mempool/blockchain transactions in general
2. Interpretation that requires knowledge about history, for example "this transaction is valid, under the aspect that a given property id does indeed exist" or "this simple send was actually a participation in a crowdsale"
3. Interpreration based on information about current mempool state - the above mentioned balance issue probably belongs here
4. Interpretation once the transaction confirmed based on information such as position within a block or information about other transactions within the same block
5. Finally and completely unrelated to the interpretation: persistence

**Comment by m21** [comment]
All very good questions & ideas guys.

As first step we could implement a lock on MP addresses with "unconfirmed" transactions -- similarly to the toggle which disallows users to spend unconfirmed transactions in Bitcoin world.

I.e. send_MP or other function sending anything out of an address which has pending confirmations will be disallowed by Master Core.

**Comment by dexX7** [comment]
> As first step we could implement a lock on MP addresses with "unconfirmed" transactions -- similarly to the toggle which disallows users to spend unconfirmed transactions in Bitcoin world.

Please don't - this seems to be the worst workaround available (sorry for the harsh words.. :). It would limit the ability to send tokens to one transaction per property per address per block.

But assuming you'd do this, then I assume this requires knowledge that there are indeed unconfirmed transactions. And if this is the case, then you probably already have the information available that might be used to calculate a temporary updated balance?

**Comment by m21** [comment]
No problem with the critique -- it for sure my "lock" proposal is clumsy. I wasn't really planning to do that, but I thought it made the most sense given your list of options from simplest to more complex one.
To prevent the case where the user thinks his transaction has long finished and issuing a new one.

Correct, we can parse the unconfirmed transaction(s) as we know them (at minimum those to/from our wallet addresses) and somehow inform the user about the expected outcome. Are there ways to game this? That's what I am worried about.

Agreed, the position of this one transaction within the block matters greatly as do positions of  all other pertinent transactions that will be included in the block with it -- all potentially affecting the final balance sheet.
We can go to great lengths trying to make pending/unconfirmed TXs somehow meaningful to the user, but I don't see us advertising the outcome with any degree of certainty no mater what we do (wallet, mempool, double-spend attempts monitoring, # of node connections, some sort of fraud statistics, etc).

Also, I am unclear how an external database could do a better job than Core itself. It would still be facing all the double-spend issues above.

**Comment by dexX7** [comment]
Yeah, you're right, any information related to unconfirmed transactions may not be reliable and should not be considered as absolute truth. I think it's best to keep things simple and focus on the actual use-case.

My main problem is that it seems quite difficult to me to answer the following question: is the balance of address X in my wallet high enough to spend an amount of Y tokens?

Currently my workaround is to use an external database to store balances which is queried before a new send is created and updated once the send was broadcasted. This is done to ensure no new transactions are created, which might turn out to be invalid due to an insufficient amount of tokens, ultimately based on the potentially inaccurate balance provided by getbalance_MP (this also affects send_MP and other balance related commands).

**Comment by m21** [comment]
Assuming everything is confirmed -- why is there difficulty deciding if you have enough funds to send?
MSC funds?

**Comment by dexX7** [comment]
In the case everything is confirmed, then there is absolutely no problem. :)

But how can I be sure that everything is indeed confirmed _without additional information_ such as an external database, or some note like "the last tx was sent hh hours ago"?

**Comment by m21** [comment]
Bitcoin core provides a way to get # of confirmations for a particular transaction: i.e. it should be at least 1.
Or visually - if you see anything unconfirmed in the QT wallet.
Or : my suggestion of a lock on an address would indicate whether any transactions associated with the address are unconfirmed.

**Comment by dexX7** [comment]
My address selection (to find a candidate for a new send) started as following, with a target currency id and amount as input:
- fetch all wallet addresses via "listaddressgroupings"
- use "getbalance_MP" on the each result with the target currency
- if the balance is high enough, I take it

What you propose is half of a solution. I could then check, if there are pending transactions for this address ("listunspent 0 0 address" should work with some further assumptions) and if there is a fresh output, I would have to skip the address and move on to the next, because I still have no clue, if the unconfirmed transaction drains the balance to a level which might prevent a successful spent.

Maintaining another DB outside of Core is easier in the sense that the amount of queries is reduced and I get accurate amounts related to my own outgoing transactions. Besides the additional overhead this doesn't count incoming unconfirmed transactions, but it wouldn't be safe to spend those anyway.

Nevertheless, long story short: I stick to the proposal of adding a new state information of "unconfirmed balance" or similar which is refreshed once a new tx hits the mempool or wallet.

Or the support of parsing unconfirmed Mastercoin transactions instead of throwing an error as mentioned in the first post would be awesome, too. :) It's probably possible to chain the commands in some way to derive an accurate unconfirmed balance from there on.

**Comment by m21** [comment]
I gotta put this here guys :)

" it's a massive-multiplayer chess-engine you want -- any move anyone else can make out there within 10 minutes that'll be randomly ordered, which you may or may not even hear in time  -- what will the outcome for the universal balance sheet be -- figure that out"

All we can state with certainty is which RPC call the user executed. That's it. Anything else is pointless.

**Comment by dexX7** [comment]
Haha that's an awesome comment. :)

It's the same with Bitcoin Core's mempool, but with more complexity. The baseline is the same though: the mempool only represents a temporaray state. Nevertheless, you'd never be able to spend more coins than Bitcoin Core thinks are available.

I feel like those are seperate issues, but creating a "decoderawtransaction_MP" call or unlimiting the current "getrawtransaction_MP" to allow unconfirmed tx can yield a similar end result:

``` bash
> mastercore-cli decoderawtransaction_MP 0100000001afa4d1...ac00000000 (some raw tx hex)
{
    "type": 0,
    "version": 0,
    "property": 3,
    "amount": 12000
}
```

Chained with other commands this would allow to reconstruct the temporary balance, too.

**Comment by dexX7** [comment]
Just wanted you to know: this seems to be a harder nut to crack, but not impossible. Key is to break down populateRPCTransactionObject and parseTransaction and removing the following blocker:

``` c++
if ((0 == blockHash) || (NULL == mapBlockIndex[blockHash])) { return MP_TX_UNCONFIRMED; }

CBlockIndex* pBlockIndex = mapBlockIndex[blockHash];
if (NULL == pBlockIndex) { return MP_BLOCK_NOT_IN_CHAIN; }

if (p_txlistdb->exists(wtxid)) { ... }
```

... already returns some results - not very great ones, but Simple Sends are parsed completely (valid = false), crowdsales are not very filled with details though.

**Comment by dexX7** [comment]
This is sort of related to #137. While there are several areas where behavior in relation of unconfirmed transactions can be improved, there is no immedient task and the initial issue was addressed. /close
