### ISSUE TITLE
Add possibility for excluded addresses in "send to owners"

### ISSUE THREAD

**Issue by amirza1** [mastercoin-MSC/mastercore#94]
Will it be possible to add 
an optional parameter list to the send to owners functionality (sendtoowners_MP) which contains
a list of excluded addresses, which will not receive any dividend?

Since there is currently no way to re-issue a smart property or burn it, one needs to issue a large initial amount, and possibly recycle it. This means there is at least one address which is not a true owner and holds a very large amount of the property with respect to all the other ones. 
It may not be the one issuing the command (which may just be some hot wallet), so one needs to 
avoid sending any dividends to it. 

Thanks,
Amir

**Comment by zathras-crypto** [comment]
This is less a question of implementation and more a question of whether the protocol is to support exclusions in these types of features.  We cannot exclude something specifically in one implementation (even the reference), we must handle exclusions at the protocol level.

Thus the send to owners transaction message must have some method of including exclusions in the broadcast for this to be possible, which I'm not sure is feasible.

@Marv @JR, feedback?

Thanks
Z

**Comment by ripper234** [comment]
IMO the proper solution would be to implement actually burning and creating fresh tokens. This seems to me more useful than this exclusion list, and it should answer this need as well.

**Comment by amirza1** [comment]
I agree that is the proper solution.
The only question is whether or not it can be implemented and tested in
time.

Amir

**Comment by dexX7** [comment]
Really interesting problem. I'm with @ripper234 here, those features would be very useful. It's not a general solution for blacklisting/whitelisting dividend receivers, but that's not what was intended to do here anyway, as it seems.

---

Some theoretical brainstorming, let's assume the following:

Do not limit "send to owners" transactions to the same currency/property, but also allow to send some amount of property A to all owners of property B.

Property type B tokens could then be used as a marker for all recipients who are eligible of receiving a dividend of type A. It's basically a whitelist approach.

I believe this would be rather easy to implement, given that 1. "send to owners" transactions already exist and 2. adding the ability to do "inter-currency send to owner" transactions actually reduces logic, namely it removes the limit-to-same-property constraint.

Nevertheless, depending on the actual use-case this could introduce some overhead or might not be useful at all. There would be a tight coupling between type A and B tokens which cannot be enforced - worst case example: a user sends his "dividend marker token B" to the cold wallet.

**Comment by amirza1** [comment]
As @ripper234 said, and I agree, this would be a non-issue if burning and asset re-issuing were supported. I also think that whitelisting or blacklisting certain owners (other than a burning address and the issuing one) is not something that should be supported by the protocol.

While I think that creating a shadow currency tagging dividend owners is a relevant solution, I'd rather it be a blacklisting mechanism and not a whitelisting, since this will allow better control if we assume the blacklisted addresses are all owned by the issuer's organization. 

I know this may seem a bit more convoluted than having a whitelist, protocol-wise, but I think it will be easier to implement. Anyway, I don't seem to have a good solution for this issue right now, and would probably be forced to hold an extremely large amount of currency in a hot wallet...

Amir

**Comment by m21** [comment]
@amirza1 

we can't do anything in the implementation until it's documented in the spec, protocol-level-wise.

Please re-open the issue here: https://github.com/mastercoin-MSC/spec/issues

**Comment by ripper234** [comment]
[spec issue 180](https://github.com/mastercoin-MSC/spec/issues/180) should be merged into the spec.

@CraigSellars FYI
